services:
  - type: web
    name: tracker-server
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: ${MONGO_URI} 
